language: node_js
node_js: stable
script:language: node_js
node_js: stable
script:
    - yarn
    - yarn test
    - yarn build

after_success: yarn coverage

deploy:
  provider: heroku
  api_key:
    secure: GOQSBZfl1aTYCHsN18OngsF7sT9/P7NfplLqzp32V+i0GyCn0Zyv4qKN6oK2TPCGadD53lsOe8H4g5nlZHLiBUrKhbEjJ7UWRhtwK1uE9xRSrFsYCfuX1FPH315gDP69rqMC/JeWCkSLfcAmKDxrz1+pbI7akOP4FOjemOmaYoU=
  app: react-shadow
  on:
    repo: Wildhoney/ReactShadow
