language: node_js
node_js: stable
script:
    - yarn
    - yarn test
    - yarn build

after_success: yarn coverage

deploy:
  provider: heroku
  api_key:
    secure: IHOnABM1cWPUyrlaMdXORUt58d/vPVgTe2uKE+VQ0dTB0AdVcTXWIwBMB6DjzkVulbdD+g51cFGP/p1pq1x009By40mWqx7Ls6UtrpWa/TDItgNwesqin/FYCh9fB7jOq0IBgoJT9gbNFfJMhku69uqpq+qFZo3K7Nx8Js6vgxk=
  app: react-shadow
  on:
    repo: Wildhoney/ReactShadow
